FROM node:12.18.3-alpine3.10 as clientBuild
ARG API_BASE_URL 

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN REACT_APP_API_BASE_URL=${API_BASE_URL} npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=clientBuild /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]