version: "3.1"

services:
  server:
    image: probable-memory/server:prod
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL:-mongodb://db:27017}
      - PORT=${PORT:-5000}
      - SECRET_KEY=${SECRET_KEY:-CheckTHISisN0tC00!}
    ports:
      - ${PORT:-5000}:5000
    links:
      - db
    restart: always
    networks:
      - stack

  client:
    image: probable-memory/client:prod
    ports:
      - ${PORT:-3000}:80
    links:
      - server
    restart: always
    networks:
      - stack

  db:
    image: mongo:4.4-bionic
    ports:
      - ${PORT:-27018}:27017
    restart: always
    networks:
      - stack

networks:
  stack:
    driver: bridge
