version: "3.1"

services:
  client:
    image: probable-memory/client:prod
    ports:
      - ${PORT:-3000}:80
    links:
      - server
    restart: always
    networks:
      - stack

networks:
  stack:
    driver: bridge
